[project]
name = "beccalossi-temp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "loguru>=0.7.3",
    "lxml==5.4",
    "seleniumbase>=4.36.4",
    "soccerdata>=1.8.2",
]
